### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by cancundeyingzi** [donno2048/DDos#5]
Traceback (most recent call last):
  File "D:\py\dos攻击\main.py", line 2, in <module>
    DDos(input("Give me a URL: "))
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python310\lib\site-packages\DDos\__init__.py", line 10, in DDos
    assert checkUrl(url)
AssertionError

未使用代理

**Comment by donno2048** [comment]
Well, that means the URL is invalid, what URL did you use?
It should be of the form `http://XXXXX.xxx`

**Comment by cancundeyingzi** [comment]
I tried using 192.168.*. on the LAN. *, and some other common URLs seem to get this error. I don't know if there is something wrong with my side of the network.

**Comment by donno2048** [comment]
> I tried using 192.168.*. on the LAN.

First of all the wildcard is invalid, second of all even when running on an IP or a socket the `checkUrl` expects a protocol

**Comment by cancundeyingzi** [comment]
I didn't use wildcards, what I meant was that I tried to access several devices that I have on my LAN. None of them could succeed. I will try again later.

**Comment by cancundeyingzi** [comment]
I use machine translation, so there may be some translation errors hope you can understand

**Comment by donno2048** [comment]
As I said "even when running on an IP or a socket the `checkUrl` expects a protocol"

**Comment by cancundeyingzi** [comment]
Yes, I saw that, so I said I would keep trying later (I have some other work on hand at the moment.) Thanks!

**Comment by donno2048** [comment]
Closing for now, feel free to reopen if the problem reoccurs.
